version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: django-docker-template-prod
    command: gunicorn -c gunicorn.conf.py
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    # expose only available within Docker network
    # expose:
    #   - 8000
    # ports available outside Docker network
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.prod
    env_file:
      - ./env/.env.prod

volumes:
  static_volume:
  media_volume:
