# Generated by Django 5.2.5 on 2025-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tagmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
